gameMode: 'Classic'
gameSpeed: 400
initialPlayerAmmoCount: 20
initialAIAmmoCount: 500

minAmmoBonusOnMap: 25
maxAmmoBonusOnMap: 30
minAmmoBonusLifeCycle: 30
maxAmmoBonusLifeCycle: 60
ammoBonusGenerationCycle: 40
ammoQuantityInAmmoBonus: 10

minHedgeHogsOnMap: 30
maxHedgeHogsOnMap: 45
ticksToUpdateHedgehogs: 10
maxHedgehogLifetime: 50
minHedgehogLifetime: 30
playerTicksPerBullet: 4
aiTicksPerBullet: 1

medKitBonusLifeCycle: 70
minMedKitBonusOnMap: 10
maxMedKitBonusOnMap: 10
minMedKitBonusLifeTime: 70
maxMedKitBonusLifeTime: 70

minBogsOnMap: 0
maxBogsOnMap: 0
ticksToUpdateBogs: 10
maxBogLifetime: 20
minBogLifetime: 10

minSandsOnMap: 0
maxSandsOnMap: 0
ticksToUpdateSands: 10
maxSandLifetime: 20
minSandLifetime: 10

minMoatsOnMap: 0
maxMoatsOnMap: 0
ticksToUpdateMoats: 10
maxMoatLifetime: 20
minMoatLifetime: 10
