gameMode: 'PlayersOnly'
gameSpeed: 200
initialPlayerAmmoCount: 100
initialAIAmmoCount: 200

ammoBonusCountOnMap: 5
minAmmoBonusLifeCycle: 30
maxAmmoBonusLifeCycle: 40
ammoBonusGenerationCycle: 40
ammoQuantityInAmmoBonus: 5

maxHedgeHogsOnMap: 0
ticksToUpdateHedgehogs: 0
maxHedgehogLifetime: 0
minHedgehogLifetime: 0
playerTicksPerBullet: 4
aiTicksPerBullet: 1

medKitBonusLifeCycle: 40
minMedKitBonusOnMap: 2
maxMedKitBonusOnMap: 4
minMedKitBonusLifeTime: 30
maxMedKitBonusLifeTime: 40
