gameMode: 'Classic'
gameSpeed: 400
initialPlayerAmmoCount: 20
initialAIAmmoCount: 500

ammoBonusCountOnMap: 10
minAmmoBonusLifeCycle: 30
maxAmmoBonusLifeCycle: 40
ammoBonusGenerationCycle: 40
ammoQuantityInAmmoBonus: 5

maxHedgeHogsOnMap: 20
ticksToUpdateHedgehogs: 10
maxHedgehogLifetime: 20
minHedgehogLifetime: 10
playerTicksPerBullet: 4
aiTicksPerBullet: 1

medKitBonusLifeCycle: 40
minMedKitBonusOnMap: 5
maxMedKitBonusOnMap: 10
minMedKitBonusLifeTime: 30
maxMedKitBonusLifeTime: 40
